# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c9f084af49dd369d53ab4ad05216fd4540725302481d2790cbc25900217aa222be0f6383fad1777a85a7bdfd7839b98bd5804fb1a936887eee5a2a4cc124d35

test:
  secret_key_base: 290ba80f24ed1d5cac4209095d017f2c59e10015729f5dcd87ff9a8002066c9c245a4d8c68a65402986a6fa4f5f9d4ce59ecd93a9180a28c25ebe0bfc4877d34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
